#!/usr/bin/perl


$class_name = $ARGV[0];

print "Generating Class $class_name\n";

$link_def_name = "$class_name"."LinkDef.h";
#-------------------------------------------------------
#  Writing The LinkDef File
#
open(LINKDEF,">$link_def_name");
print LINKDEF "#ifdef __CINT__\n";
print LINKDEF "#pragma link off all globals;\n";
print LINKDEF "#pragma link off all classes;\n";
print LINKDEF "#pragma link off all functions;\n\n";
print LINKDEF "#pragma link C++ class $class_name;\n";
print LINKDEF "#endif\n";
#print LINKDEF "";
close(LINKDEF);
#--------------------------------------------------------
#  Writing the Header (.h) file
#
$date_line   = `date`;
chop($date_line);
$header_name = "$class_name".".h";
open(HFILE,">$header_name");

print HFILE "// Autogenerated Class (Header File)\n";
print HFILE "// Author : G.Gavalian\n";
print HFILE "// Date   : $date_line\n";
print HFILE "//\n\n";
print HFILE "#ifndef __$class_name\__\n";
print HFILE "#define __$class_name\__\n";
print HFILE "#include <iostream>\n";
print HFILE "#include <TROOT.h>\n";
print HFILE "#include <TVector3.h>\n";
print HFILE "#include <TObject.h>\n";
print HFILE "\n\n";
print HFILE "class $class_name : public TObject \{\n";
print HFILE "private:\n\n";
print HFILE "public:\n";
print HFILE "$class_name ();\n";
print HFILE "~$class_name ();\n\n";
print HFILE "ClassDef($class_name,1)\n\n";
print HFILE "\n\};\n";
print HFILE "";

print HFILE "";
print HFILE "#endif\n";
close(HFILE);
#--------------------------------------------------
#  Writing The Source (.cc) FILE
#

$src_name = "$class_name".".cc";
open(SRCFILE,">$src_name");

print SRCFILE "// Autogenerated Class (Source File)\n";
print SRCFILE "// Author : G.Gavalian\n";
print SRCFILE "// Date   : $date_line\n";
print SRCFILE "//\n\n";

print SRCFILE "#include \"$header_name\"\n";
print SRCFILE "\n\n";
print SRCFILE "\nClassImp($class_name)\n\n\n";

print SRCFILE "$class_name\::$class_name (){\n\n}\n\n";
print SRCFILE "$class_name\::~$class_name (){\n\n}\n\n";
print SRCFILE "//-----------------\n";
print SRCFILE "//-----------------\n";
print SRCFILE "//-----------------\n";
print SRCFILE "";
print SRCFILE "";
print SRCFILE "";
print SRCFILE "";

close(SRCFILE);
