// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Tue Jul 21 08:39:39 EDT 2009
//

#include "TClasParticle.h"



ClassImp(TClasParticle)


TClasParticle::TClasParticle (){

}

TClasParticle::~TClasParticle (){

}

TClasParticle::TClasParticle(const TClasParticle &part)
{
  *this = part;
}
//-----------------
//-----------------
void   TClasParticle::SetId(int id)
{
  TParticlePDG *ptr_PART = TDatabasePDG::Instance()->GetParticle(id);
  // if Particle not found in the database
  if(ptr_PART==NULL)
    {
      printf("TClasParticle::ERROR: Particle with %d id is not found\n ",id);
      pdgID = 0;
      return;
    }
  pdgID   = id;
  pdgMass = ptr_PART->Mass();
}

void   TClasParticle::SetPartById(int id, TVector3 p3, TVector3 v3)
{
   TParticlePDG *ptr_PART = TDatabasePDG::Instance()->GetParticle(id);
  // if Particle not found in the database
  if(ptr_PART==NULL)
    {
      printf("TClasParticle::ERROR: Particle with %d id is not found\n ",id);
      pdgID = 0;
      return;
    }

  pdgID = id;
  pdgMass = ptr_PART->Mass();
  fPartVector.SetVectM(p3,pdgMass);
  fPartVertex = v3;
}

void   TClasParticle::Reset()
{
  pdgID   = 0;
  pdgMass = 0.;
  tofMass = 0.;
  fPartVector.SetPxPyPzE(0.,0.,0.,0.);
  fPartVertex.SetXYZ(0.,0.,0.);
  partCharge = 0;
  SetStatus(-1);
}
//-----------------
TClasParticle &TClasParticle::operator=(const TClasParticle &part)
{ 
  return *this;
}

string  TClasParticle::particleToStringLund()
{
  stringstream strOut;
  strOut << setw(7)  << GetPdgId();
  strOut << setw(12) << setprecision(5) << pdgMass;
  strOut << setw(12) << setprecision(5) << fPartVector.Px();
  strOut << setw(12) << setprecision(5) << fPartVector.Py();
  strOut << setw(12) << setprecision(5) << fPartVector.Pz();
  strOut << setw(12) << setprecision(5) << fPartVertex.X();
  strOut << setw(12) << setprecision(5) << fPartVertex.Y();
  strOut << setw(12) << setprecision(5) << fPartVertex.Z();
  return strOut.str();
}

TString          TClasParticle::ToString()
{
  TString res = particleToStringLund().c_str();
  return res;
}
