// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Tue Jul 14 09:19:55 EDT 2009
//

#ifndef __TPartCounter__
#define __TPartCounter__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TString.h>
#include <vector>
#include <TDatabasePDG.h>
#include <TObjArray.h>
#include <TObjString.h>

using namespace std;


class TPartCounter : public TNamed {

private:

  vector<int> fPartIDStore;
  vector<int> fPartStatus;

  int         fPartOffCountCharged;
  int         fPartOffCountNeutral;

public:

  TPartCounter ();
  ~TPartCounter ();


 void   SetPartInfo(const char *partList);
 void   ClearCount();
 void   AddParticle(int id);
 int    GetNextFreeIndex(int id);
 int    GetStatus();
 // void   PrintInfo();
ClassDef(TPartCounter,1)

};
#endif
