// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Thu Jul 16 01:48:44 EDT 2009
//

#include "TParameterStore.h"



ClassImp(TParameterStore)


TParameterStore::TParameterStore (){

}

TParameterStore::~TParameterStore (){

}

//-----------------
//-----------------
//-----------------
void       TParameterStore::AddParameter(const char *_parname, const char *_parvalue){}
void       TParameterStore::SetParameter(const char *_parname, const char *_parvalue){}
Bool_t     TParameterStore::Contains(const char *_parname){}
TString    TParameterStore::GetStringValue(const char *_parname){}
Double_t   TParameterStore::GetDoubleValue(const char *_parname){}
Int_t      TParameterStore::GetIntValue(const char *_parname){}
