// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Thu Jul 16 01:48:44 EDT 2009
//

#ifndef __TParameterStore__
#define __TParameterStore__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TUserParameter.h>
#include <TObjArray.h>

class TParameterStore : public TObject {
private:

  TObjArray  fParArray;

public:

TParameterStore ();
~TParameterStore ();


 void       AddParameter(const char *_parname, const char *_parvalue);
 void       SetParameter(const char *_parname, const char *_parvalue);
 Bool_t     Contains(const char *_parname);
 TString    GetStringValue(const char *_parname);
 Double_t   GetDoubleValue(const char *_parname);
 Int_t      GetIntValue(const char *_parname);


ClassDef(TParameterStore,1)


};
#endif
