// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Thu Jul 16 01:32:08 EDT 2009
//

#include "TUserParameter.h"



ClassImp(TUserParameter)


TUserParameter::TUserParameter (){
  Set("NULL","NULL");
}

TUserParameter::~TUserParameter (){

}

//-----------------
//-----------------
//-----------------
TUserParameter::TUserParameter (const char *pname, const char *pval)
{Set(pname,pval);}
