#!/bin/sh
echo BUILDS=$BUILDS
echo CERN_ROOT=$CERN_ROOT
echo CLAS_BIN=$CLAS_BIN
echo CLAS_BUILD=$CLAS_BUILD
echo CLAS_CMS=$CLAS_CMS
echo CLAS_LIB=$CLAS_LIB
echo CLAS_PACK=$CLAS_PACK
echo CLAS_PARMS=$CLAS_PARMS
echo CLAS_ROOT=$CLAS_ROOT
echo CLAS_SCRIPTS=$CLAS_SCRIPTS
echo CLAS_SLIB=$CLAS_SLIB
echo CLAS_TOOLS=$CLAS_TOOLS
echo CVSROOT=$CVSROOT
echo OS_NAME=$OS_NAME
echo TOP_DIR=$TOP_DIR
