// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Sat Mar  1 14:15:12 EST 2008
//

#ifndef __TCLASCorrectionsGSIM__
#define __TCLASCorrectionsGSIM__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TLorentzVector.h>
#include "TCLASCorrectionBase.h"

class TCLASCorrectionsGSIM : public TCLASCorrectionBase {
private:

public:
TCLASCorrectionsGSIM ();
~TCLASCorrectionsGSIM ();

 void  Init(int mode = 0);

 TLorentzVector   GetVector(TLorentzVector  vPin, int charge, int type);
 TLorentzVector   GetTagger(TLorentzVector vG, int E_ID, int RunNum);
  
ClassDef(TCLASCorrectionsGSIM,1)



};
#endif
