// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Sat Mar  1 14:04:57 EST 2008
//

#include "TCLASCorrections.h"



ClassImp(TCLASCorrections)


TCLASCorrections::TCLASCorrections (){

}

TCLASCorrections::~TCLASCorrections (){

}

//-----------------
//-----------------
//-----------------
