// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Sat Mar  1 14:06:29 EST 2008
//

#ifndef __TCLASCorrectionBase__
#define __TCLASCorrectionBase__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TLorentzVector.h>

class TCLASCorrectionBase : public TObject {

private:

public:
TCLASCorrectionBase ();
~TCLASCorrectionBase ();


 virtual  void  Init(int mode = 0);

 virtual  TLorentzVector   GetVector(TLorentzVector  vPin, int charge, int type);
 virtual  TLorentzVector   GetTagger(TLorentzVector vG, int E_ID, int RunNum);
  
ClassDef(TCLASCorrectionBase,1)


};
#endif
