// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Mon Mar 10 13:26:55 EDT 2008
//

#ifndef __TCLASCorrectionsG10D__
#define __TCLASCorrectionsG10D__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TLorentzVector.h>

#include "TCLASCorrectionBase.h"
#include "include/g10_tagger_corrections.h"

class TCLASCorrectionsG10D : public TCLASCorrectionBase {

private:

public:

TCLASCorrectionsG10D ();
~TCLASCorrectionsG10D ();

 void  Init(int mode = 0);

 TLorentzVector   GetVector(TLorentzVector  vPin, int charge, int type);
 TLorentzVector   GetTagger(TLorentzVector vG, int E_ID, int RunNum);

ClassDef(TCLASCorrectionsG10D,1)



};
#endif
