// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Mon Mar 10 13:26:55 EDT 2008
//

#include "TCLASCorrectionsG10D.h"



ClassImp(TCLASCorrectionsG10D)


TCLASCorrectionsG10D::TCLASCorrectionsG10D (){

}

TCLASCorrectionsG10D::~TCLASCorrectionsG10D (){

}

//-----------------
//-----------------
//-----------------

void  TCLASCorrectionsG10D::Init(int mode)
{
  printf("\n");
  printf("********************************************\n");
  printf("* TCLAS Corrections G10D Initialized       *\n");
  printf("********************************************\n");
  printf("\n");
}

TLorentzVector   TCLASCorrectionsG10D::GetVector(TLorentzVector  vPin, int charge, int type)
{
  return vPin;
}

TLorentzVector   TCLASCorrectionsG10D::GetTagger(TLorentzVector vG, int E_ID, int RunNum)
{
  double   eg = vG.E();
  if(E_ID<=0||E_ID>767){
    printf("G10TaggeCORR:: Error in EID number (%d)\n",E_ID);
    return vG;
  }
  double  neg = eg*TG10Tagger::G10TAGGCORR[E_ID-1];
  TLorentzVector vG_new(0.,0.,neg,neg);
  return vG_new;
}
