// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Sat Mar  1 14:15:12 EST 2008
//

#include "TCLASCorrectionsGSIM.h"



ClassImp(TCLASCorrectionsGSIM)


TCLASCorrectionsGSIM::TCLASCorrectionsGSIM (){

}

TCLASCorrectionsGSIM::~TCLASCorrectionsGSIM (){

}

//-----------------
//-----------------
//-----------------
void  TCLASCorrectionsGSIM::Init(int mode)
{
}

TLorentzVector   TCLASCorrectionsGSIM::GetVector(TLorentzVector  vPin, int charge, int type)
{
}
TLorentzVector   TCLASCorrectionsGSIM::GetTagger(TLorentzVector vG, int E_ID, int RunNum)
{
}
