// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Sat Mar  1 14:14:02 EST 2008
//

#ifndef __TCLASCorrectionsG11A__
#define __TCLASCorrectionsG11A__
#include <iostream>
#include <cmath>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>
#include <TLorentzVector.h>
#include "TCLASCorrectionBase.h"
#include <TF1.h>

#include "include/g11a_correction_data.h"
#include "include/g11a_correction_bins.h"
#include "include/g11_taggercorrection.h"

class TCLASCorrectionsG11A : public TCLASCorrectionBase {

private:

  TF1  *func_P3;
  TF1  *func_P4;

public:

TCLASCorrectionsG11A ();
~TCLASCorrectionsG11A ();

 void  Init(int mode = 0);

 TLorentzVector   GetVector(TLorentzVector  vPin, int charge, int type);
 TLorentzVector   GetTagger(TLorentzVector vG, int E_ID, int RunNum);

/*  double    GetLambdaTrack(TVector3 v3); */
/*  double    GetPhiTrack(TVector3 v3); */
 double      GetLambdaTrack(double v3_[]);
 double      GetPhiTrack(double v3_[]);
 double      GetFunc_p(double _p,int charge, int bin, int sector);
 double      GetFunc_phi(double _p,int charge, int bin, int sector);
 double      GetFunc_lam(double _p,int charge, int bin, int sector);


 void        GetFuncLambda(TF1 *f1);
 void        SetP3FromTrackingParameters(double __p,double __lam,double __phi,
				 int __sector,double __p3[3]);

 double    GetSectorPhi(double __phi);
 int       GetBin(double __theta,double __phi);
 int       GetSector(double __p3[3]);

ClassDef(TCLASCorrectionsG11A,1)


};
#endif
