// Autogenerated Class (Source File)
// Author : G.Gavalian
// Date   : Sat Mar  1 14:06:29 EST 2008
//

#include "TCLASCorrectionBase.h"


ClassImp(TCLASCorrectionBase)


TCLASCorrectionBase::TCLASCorrectionBase (){

}

TCLASCorrectionBase::~TCLASCorrectionBase (){

}

//-----------------
//-----------------
//-----------------

void  TCLASCorrectionBase::Init(int mode)
{
  printf("\nTCLASCorrectionBase:: This is a base class.\n\n");
}

TLorentzVector   TCLASCorrectionBase::GetVector(TLorentzVector  vPin, int charge, int type)
{
  TLorentzVector a;
  printf("\nTCLASCorrectionBase:: This is a base class.\n\n");
  return a;
}
TLorentzVector   TCLASCorrectionBase::GetTagger(TLorentzVector vG, int E_ID, int RunNum)
{
  TLorentzVector a;
  printf("\nTCLASCorrectionBase:: This is a base class.\n\n");
  return a;
}
