// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Sat Mar  1 14:04:57 EST 2008
//

#ifndef __TCLASCorrections__
#define __TCLASCorrections__
#include <iostream>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>


class TCLASCorrections : public TObject {
private:

public:
TCLASCorrections ();
~TCLASCorrections ();

ClassDef(TCLASCorrections,1)


};
#endif
