// Autogenerated Class (Header File)
// Author : G.Gavalian
// Date   : Fri Feb 29 16:56:45 EST 2008
//

#ifndef __TFuncIntercept__
#define __TFuncIntercept__
#include <iostream>
#include <cmath>
#include <TROOT.h>
#include <TVector3.h>
#include <TObject.h>


class TFuncIntercept : public TObject {
private:

public:

TFuncIntercept ();
~TFuncIntercept ();

 void   InterCylinder(double vertex[],double cdir[],double center[], double d[], double r, double x[], int *ierr);
 
 void   IntersectionPlane(double m1[], double m2[],double m0[],double n[],double m[],int *rep);
 void   IntersectionSphere(double m1[],double m2[],double m0[], double r, double m[], double mm[], int *rep);
 void   IntersectionCone(double m1[],double m2[],double m0[],double d[],double alpha, double m[],double mm[],int *rep);

 void  IntersectionCylindre(double m1[],double  m2[],double  m0[], double d[],double r, double m[],double  mm[], int *rep);

ClassDef(TFuncIntercept,1)


};
#endif
