#define DISPLAY_CHARGES(A1,A2,A3,A4,A5,A6,A7) CCALLSFSUB7(DISPLAY_CHARGES,display_charges,INT,FLOATV,INT,INT,INT,INT,INT,A1,A2,A3,A4,A5,A6,A7)

#define DISPLAY_PROJ_POS(A1,A2,A3) CCALLSFSUB3(DISPLAY_PROJ_POS,display_proj_pos,FLOAT,FLOAT,INT,A1,A2,A3)
