#!/usr/bin/perl

$BankName = $ARGV[0];
$BankNameCLASS = uc($BankName);
print "Creating File ->> $BankName ($BankNameCLASS)\n";
$BankFileName = "$BankName".".ddl";

open(FILE_IN,$BankFileName);

$iCount = 0;

$BankVariables = "";
$BankVariablesTypes = "";

while(<FILE_IN>)
{
    chop($_);
    @str_line = split (' ',$_);

    $idx_EXCL = index("!",$str_line[0]);
    $idx_HEAD = index("TABLE",$str_line[0]);

    if(index($str_line[0],"!")==0||index($str_line[0],"TABLE")==0||index($str_line[0],"END")==0)
    {

    } else {

	print "Line $_ is a comment $idx_EXCL ($str_line[0])  $idx_HEAD\n";
	if($iCount!=0)
	{
	    $BankVariables = "$BankVariables".":";
	    $BankVariablesTypes =  "$BankVariablesTypes".":";
	}
	$TypeLocal = "unknown";
	if(index("F",$str_line[2])==0){
	    $TypeLocal = "Float_t";
	}

	if(index("I",$str_line[2])==0){
	    $TypeLocal = "Int_t";
	}
	
	$BankVariables = "$BankVariables"."$str_line[1]";
	$BankVariablesTypes =  "$BankVariablesTypes"."$TypeLocal";
#	print "Line $iCount is  not a comment\n";
	$iCount++;
    }


}


#---------------------------------------------------------------
#---------------------------------------------------------------
print "BankVariables = $BankVariables\n";
print "BankVariables = $BankVariablesTypes\n";


#----------------------------------------------------------------

$HEADER_FileName = "T"."$BankNameCLASS"."Class.h";
$SOURCE_FileName = "T"."$BankNameCLASS"."Class.cc";
$LINKDEF_FileName = "T"."$BankNameCLASS"."ClassLinkDef.h";
$FILL_FileName = "Fill_"."$BankNameCLASS"."_Bank.cc";
$CLASS_NAME = "T"."$BankNameCLASS"."Class";
#-- Write HEADER CLass

@BUFF_Variables = split(':',$BankVariables);
@BUFF_Types     = split(':',$BankVariablesTypes);
$NBuffer        = @BUFF_Variables;

open(FILE_H,">$HEADER_FileName");

print FILE_H "// Header File $HEADER_FileName\n";
print FILE_H "// Autogenerated\n";
print FILE_H "// Author: G.Gavalian (ODU) 2009\n";
print FILE_H "#ifndef _$CLASS_NAME\_\n";
print FILE_H "#define _$CLASS_NAME\_\n";
print FILE_H "#include <iostream>\n\n";
print FILE_H "using namespace std;\n\n";
print FILE_H "#include \"TObject.h\"\n";
print FILE_H "#include \"TString.h\"\n\n";
print FILE_H "class $CLASS_NAME : public TObject{\n";
print FILE_H "public:\n\n";
for($j=0;$j<$NBuffer;$j++)
{
    print FILE_H "$BUFF_Types[$j]  $BUFF_Variables[$j];\n";
}

print FILE_H "\n public:\n\n";
print FILE_H "$CLASS_NAME () {};\n";
print FILE_H "$CLASS_NAME ( $CLASS_NAME *Tmp);\n";
print FILE_H "virtual ~$CLASS_NAME () {};\n";
print FILE_H "void Print();\n";
print FILE_H "\nClassDef($CLASS_NAME,1)\n";
print FILE_H "};\n\n#endif\n";
close(FILE_H);

#---- Writing the CC file

open(FILE_CC,">$SOURCE_FileName");

print FILE_CC "// Source File $SOURCE_FileName\n";
print FILE_CC "// Autogenerated\n";
print FILE_CC "// Author: G.Gavalian (ODU) 2009\n";
print FILE_CC "#include \"$HEADER_FileName\"\n";
print FILE_CC "ClassImp($CLASS_NAME)\n\n";
print FILE_CC "$CLASS_NAME\::$CLASS_NAME ( $CLASS_NAME *Tmp){\n";
for($j=0;$j<$NBuffer;$j++)
{
    print FILE_CC " $BUFF_Variables[$j]  = Tmp->$BUFF_Variables[$j];\n";
}
print FILE_CC "}\n\n";
print FILE_CC "void $CLASS_NAME\::Print() {  }\n";
close(FILE_CC);
#---- Write Link Def File

open(FILE_LD,">$LINKDEF_FileName");
print FILE_LD "#ifdef __CINT__\n";
print FILE_LD "#pragma link off all globals;\n";
print FILE_LD "#pragma link off all classes;\n";
print FILE_LD "#pragma link off all functions;\n\n";
print FILE_LD "#pragma link C++ class TICHBClass;\n\n";
print FILE_LD "#endif\n";
close(FILE_LD);

#-- Write FillBank---

open(FILE_FILL,">$FILL_FileName");
print FILE_FILL "// Source File $SOURCE_FileName\n";
print FILE_FILL "// Autogenerated\n";
print FILE_FILL "// Author: G.Gavalian (ODU) 2009\n";
print FILE_FILL "#include \"TROOT.h\"\n";
print FILE_FILL "#include \"$HEADER_FileName\"\n";
print FILE_FILL "#include \"clasbanks.h\"\n";

print FILE_FILL "void  Fill_$BankNameCLASS\_Bank($CLASS_NAME *gc$BankNameCLASS,$BankNameCLASS *p$BankNameCLASS , int nrow);\n";
print FILE_FILL "void  Fill_$BankNameCLASS\_Bank($CLASS_NAME *gc$BankNameCLASS,$BankNameCLASS *p$BankNameCLASS , int nrow)\n{\n";
for($j=0;$j<$NBuffer;$j++)
{
    print FILE_FILL " gc$BankNameCLASS\->$BUFF_Variables[$j]  = p$BankNameCLASS->get_$BUFF_Variables[$j](nrow);\n";
}

print  FILE_FILL "}\n\n";
print  FILE_FILL "// End of Fill File -----------------\n\n";
close(FILE_FILL);
